language: cpp

dist: trusty

notifications:
  email: false


branches:
  only:
    - master

matrix:
  fast_finish: true

  include:

    # - os: linux
    #   compiler: "gcc-5-release"
    #   addons: &gcc5
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test']
    #       packages: ['g++-5', 'libbz2-dev', 'libstxxl-dev', 'libstxxl1', 'libxml2-dev', 'libzip-dev', 'lua5.1', 'liblua5.1-0-dev', 'libtbb-dev', 'libgdal-dev', 'libluabind-dev', 'libboost-all-dev', 'ccache']
    #   env: CCOMPILER='gcc-5' CXXCOMPILER='g++-5' BUILD_TYPE='Release'

    - os: linux
      compiler: "gcc-5-release-32bit"
      env: >
        ARCH='i386'
        REPO='ppa:ubuntu-toolchain-r/test'
        DEPS='g++-5-multilib libxml2-dev:i386 libzip-dev:i386 libbz2-dev:i386 libstxxl-dev:i386 libtbb-dev:i386 lua5.2:i386 liblua5.2-dev:i386 libluabind-dev:i386 libboost-date-time-dev:i386 libboost-filesystem-dev:i386 libboost-iostreams-dev:i386 libboost-program-options-dev:i386 libboost-regex-dev:i386 libboost-system-dev:i386 libboost-thread-dev:i386 libboost-test-dev:i386'
        CCOMPILER='gcc-5 -m32' CXXCOMPILER='g++-5 -m32' BUILD_TYPE='Release'

before_install:
  # Make sure apt is up to date.
  #- sudo add-apt-repository --remove ppa:whatever/ppa
  #- sudo rm -rf /etc/apt/sources.list.d/*
  #- dpkg --print-architecture
  #- dpkg --print-foreign-architectures
  - if [ ! -z $ARCH ] ; then sudo dpkg --add-architecture $ARCH ; fi
  #- dpkg --print-foreign-architectures
  - if [ ! -z $REPO ] ; then ( sudo add-apt-repository -y $REPO && sudo apt-get update --yes ) || true ; fi
  - if [ ! -z $DEPS ] ; then sudo apt-get install --yes --force-yes $DEPS ; fi
  # - echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe multiverse restricted" >> /etc/apt/sources.list
  # - echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main universe multiverse restricted" >> /etc/apt/sources.list
  # For native code tests, we need some additional libraries if we are in a 64-bit environment.
  - grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
  - aptitude search boost
  - make

script:
  - ./sandbox

